name: robot_test_with_mocktail_examples
description: Example project for robot test with Mocktail.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  robot_test_mocktail:
    path: ../../packages/robot_test_mocktail
  very_good_analysis: ^3.1.0
