name: robot_test_mocktail
description: Mocktail support for robot_test
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.8.0
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  robot_test:
    path: ../robot_test

dev_dependencies:
  very_good_analysis: ^3.1.0

dependency_overrides:
  robot_test:
    path: ../robot_test
