name: robot_test_examples
description: Example project for robot test.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  robot_test:
    path: ../../packages/robot_test
  very_good_analysis: ^3.1.0
