name: robot_test_mockito
description: Mockito support for robot_test
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.8.0
  mockito: ^5.3.2
  robot_test:
    path: ../robot_test

dev_dependencies:
  build_runner: ^2.3.0
  very_good_analysis: ^3.1.0

dependency_overrides:
  robot_test:
    path: ../robot_test
