name: robot_test_bloc
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_test:
    sdk: flutter
  meta: ^1.8.0
  robot_test:
    path: ../../packages/robot_test

dev_dependencies:
  very_good_analysis: ^3.1.0
